train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-simple
    args:
      gt_size: 192
      augment: true
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: edsr-multi
  args:
    no_upsampling: false
  #   scale: 4

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

is_resume : False
resume: ./save/_train_edsr-multi/epoch-last.pth